# Generated by Django 5.1.6 on 2025-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
