# Generated by Django 5.1.6 on 2025-02-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0002_testingtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testingTable',
        ),
    ]
