# Generated by Django 5.1.6 on 2025-02-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0004_lines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lines',
            options={'managed': False},
        ),
    ]
