# Generated by Django 5.1.6 on 2025-02-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0005_alter_lines_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lines',
        ),
    ]
