# Generated by Django 5.1.6 on 2025-02-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0006_delete_lines'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table='Funds',
        ),
    ]
