# Generated by Django 5.1.6 on 2025-03-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0013_rename_fund_id_line_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.RemoveField(
            model_name='fund',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_cash_balance_currency',
        ),
        migrations.RemoveField(
            model_name='line',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_budget_spent_currency',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_budgeted_currency',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_encumbered_currency',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_total_income_currency',
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_cash_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sof',
            field=models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budget_spent',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budgeted',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_encumbered',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_total_income',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddField(
            model_name='fund',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept'),
        ),
        migrations.AddField(
            model_name='line',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(max_length=11)),
                ('hire_date', models.DateField()),
                ('yos', models.FloatField()),
                ('job_title', models.CharField(max_length=255)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_type', models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=50)),
                ('fund_year', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('line_item', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('fee_based', models.BooleanField()),
                ('month', models.IntegerField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.line')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
