# Generated by Django 5.1.6 on 2025-03-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0014_dept_remove_fund_dept_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='fund_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
