# Generated by Django 5.1.6 on 2025-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0015_testing_fund_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sof',
            field=models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=10, verbose_name='Source of Funds'),
        ),
    ]
