# Generated by Django 5.1.6 on 2025-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0016_alter_dept_dept_id_alter_fund_sof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_name',
            field=models.CharField(max_length=255, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pay Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(max_length=11, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='yos',
            field=models.FloatField(verbose_name='Years of Service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_cash_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fund Cash Balance'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.SmallIntegerField(blank=True, primary_key=True, serialize=False, verbose_name='Fund ID'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_name',
            field=models.CharField(max_length=255, verbose_name='Fund Name'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='mac_elig',
            field=models.BooleanField(verbose_name='Medicaid Administrative Claiming Eligibility'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fee_based',
            field=models.BooleanField(verbose_name='Fee Based'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fund_type',
            field=models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=50, verbose_name='Fund Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fund_year',
            field=models.IntegerField(verbose_name='Fund Year'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='line_item',
            field=models.CharField(max_length=255, verbose_name='Line Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='month',
            field=models.IntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='line',
            name='cofund',
            field=models.CharField(max_length=3, verbose_name='CoFund'),
        ),
        migrations.AlterField(
            model_name='line',
            name='county_code',
            field=models.CharField(max_length=4, verbose_name='County Code'),
        ),
        migrations.AlterField(
            model_name='line',
            name='fund_year',
            field=models.SmallIntegerField(verbose_name='Fund Year'),
        ),
        migrations.AlterField(
            model_name='line',
            name='gen_ledger',
            field=models.IntegerField(verbose_name='General Ledger'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budget_spent',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Line Budget Spent'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budgeted',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Line Budgeted'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_encumbered',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Line Encumbered'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Line ID'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_name',
            field=models.CharField(max_length=255, verbose_name='Line Name'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_total_income',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Line Total Income'),
        ),
    ]
