# Generated by Django 5.1.6 on 2025-03-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0017_alter_dept_dept_name_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('ein', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('void', models.BooleanField(default=False)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('vendor_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_num', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Issue', 'Issue'), ('Pay', 'Pay')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('warrant', models.CharField(blank=True, max_length=50, null=True)),
                ('prid', models.CharField(blank=True, max_length=50, null=True)),
                ('grli', models.CharField(blank=True, max_length=50, null=True)),
                ('odhafr', models.CharField(blank=True, max_length=50, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
        ),
    ]
