# Generated by Django 5.1.6 on 2025-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0018_people_invoice_purchaseorder_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='vendor_customer',
            new_name='people',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Invoice Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='void',
            field=models.BooleanField(default=False, verbose_name='Void'),
        ),
        migrations.AlterField(
            model_name='people',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='people',
            name='ein',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='EIN'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Name ID'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='people',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='people',
            name='state',
            field=models.CharField(max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='people',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grli',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grant Line Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='odhafr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Annual Financial Report'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Purchase Order Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='prid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Program ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='type',
            field=models.CharField(choices=[('Issue', 'Issue'), ('Pay', 'Pay')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warrant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Warrant'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Voucher ID'),
        ),
    ]
