# Generated by Django 5.1.6 on 2025-03-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0021_alter_invoice_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people'),
        ),
    ]
