# Generated by Django 5.1.6 on 2025-03-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0022_alter_invoice_people'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='Invoices',
        ),
        migrations.AlterModelTable(
            name='people',
            table='Peoples',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='PurchaseOrders',
        ),
        migrations.AlterModelTable(
            name='voucher',
            table='Vouchers',
        ),
    ]
