# Generated by Django 5.1.6 on 2025-03-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0023_alter_invoice_table_alter_people_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='fund',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund'),
        ),
    ]
