# Generated by Django 5.1.6 on 2025-03-25 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0026_alter_testing_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund'),
        ),
    ]
