# Generated by Django 5.1.6 on 2025-03-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0027_alter_testing_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='fund',
        ),
    ]
