# Generated by Django 5.1.6 on 2025-03-26 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0028_remove_testing_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund'),
            preserve_default=False,
        ),
    ]
