# Generated by Django 5.1.6 on 2025-03-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0029_testing_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetActions',
            fields=[
                ('ba_id', models.AutoField(primary_key=True, serialize=False)),
                ('ba_date', models.DateField()),
                ('fssf_from', models.CharField(max_length=20)),
                ('fssf_to', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved', models.BooleanField(default=False)),
                ('fs_res_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Budget Actions',
            },
        ),
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('odhafr', models.CharField(max_length=10)),
                ('rev_gen', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('fphs', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
            ],
            options={
                'db_table': 'Activity List',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs_per_pay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pers', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medicare', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vac_elig', models.BooleanField(default=True)),
                ('vacation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('plar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sick', models.DecimalField(decimal_places=2, max_digits=15)),
                ('holiday', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_hrly', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percent_leave', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_type', models.CharField(choices=[('Single', 'Single'), ('Waived', 'Waived'), ('Emp-Spouse', 'Emp Spouse'), ('Emp-Child', 'Emp Child'), ('Family', 'Family')], max_length=10)),
                ('board_ins_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('board_share_hrly', models.DecimalField(decimal_places=2, max_digits=15)),
                ('life_rate', models.CharField(choices=[('Ineligible', 'Ineligible'), ('Rate 1', 'Rate1'), ('Rate 2', 'Rate2')], max_length=10)),
                ('life_hrly', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fringe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_comp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee')),
            ],
            options={
                'db_table': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='Carryover',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('fy', models.IntegerField()),
                ('co_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('encumbered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year_end_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('beg_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fy_beg_date', models.DateField()),
                ('fy_end_date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
            ],
            options={
                'db_table': 'Carryover',
            },
        ),
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('grant_name', models.CharField(max_length=30)),
                ('grant_year', models.PositiveSmallIntegerField()),
                ('cfda', models.CharField(max_length=8)),
                ('program_name', models.CharField(max_length=150)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pt_no', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('beg_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fsid', models.CharField(max_length=10)),
                ('funder', models.CharField(max_length=50)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
            ],
            options={
                'db_table': 'Grants',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('beg_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vacation_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sick_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comp_time_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('other_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('other_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activityList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.activitylist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
    ]
