# Generated by Django 5.1.6 on 2025-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0030_budgetactions_activitylist_benefits_carryover_grants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefits',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='fphs',
            field=models.CharField(max_length=20, verbose_name='Foundational Public Health Service'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='odhafr',
            field=models.CharField(max_length=10, verbose_name='ODHAFR'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='program',
            field=models.CharField(max_length=100, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='program_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Program ID'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='rev_gen',
            field=models.BooleanField(default=False, verbose_name='Revenue Generating'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='board_ins_share',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Board Insurance Share'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='board_share_hrly',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Board Share Hourly'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='fringe',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fringe'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='holiday',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Holiday Hours'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='hrs_per_pay',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hours Per Pay'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='ins_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Waived', 'Waived'), ('Emp-Spouse', 'Emp Spouse'), ('Emp-Child', 'Emp Child'), ('Family', 'Family')], max_length=10, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='life_hrly',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Life Hourly'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='life_rate',
            field=models.CharField(choices=[('Ineligible', 'Ineligible'), ('Rate 1', 'Rate1'), ('Rate 2', 'Rate2')], max_length=10, verbose_name='Life Insurance Rate'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='medicare',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Medicare'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='monthly_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monthly Hours'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='percent_leave',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Percent Leave'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='pers',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Public Employee Retirement System'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='plar',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Paid Leave Accumulation Rate'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='sick',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sick Leave'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='total_comp',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Compensation'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='total_hrly',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Hourly'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='vac_elig',
            field=models.BooleanField(default=True, verbose_name='Vacation Eligible'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='vacation',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Vacation'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='wc',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Workman's Compensation"),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='ba_date',
            field=models.DateField(verbose_name='Budget Action Date'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='ba_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Budget Action ID'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='fs_res_no',
            field=models.IntegerField(verbose_name='FS Res Number'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='fssf_from',
            field=models.CharField(max_length=20, verbose_name='FSSF From'),
        ),
        migrations.AlterField(
            model_name='budgetactions',
            name='fssf_to',
            field=models.CharField(max_length=20, verbose_name='FSSF To'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='beg_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Beginning Balance'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='co_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Carryover Amount'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='co_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Carryover ID'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='encumbered',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Encumbered'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='fy',
            field=models.IntegerField(verbose_name='Fiscal Year'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='fy_beg_date',
            field=models.DateField(verbose_name='Fiscal Year Beginning Date'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='fy_end_date',
            field=models.DateField(verbose_name='Fiscal Year End Date'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='year_end_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Year-End Balance'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='award_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Award Amount'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='beg_date',
            field=models.DateField(verbose_name='Beginning Date'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='cfda',
            field=models.CharField(max_length=8, verbose_name='Catalog of Federal Domestic Assistance'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='fsid',
            field=models.CharField(max_length=10, verbose_name='FSID'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='funder',
            field=models.CharField(max_length=50, verbose_name='Funder'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='grant_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Grant ID'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='grant_name',
            field=models.CharField(max_length=30, verbose_name='Grant Name'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='grant_year',
            field=models.PositiveSmallIntegerField(verbose_name='Grant Year'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='program_name',
            field=models.CharField(max_length=150, verbose_name='Program Name'),
        ),
        migrations.AlterField(
            model_name='grants',
            name='pt_no',
            field=models.CharField(max_length=8, verbose_name='Pass Through Number'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='beg_date',
            field=models.DateField(verbose_name='Beginning Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='comp_time_used',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comp Time Used'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Other Hours'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Other Rate'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Pay Amount'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Payroll ID'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='sick_used',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sick Used'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='vacation_used',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Vacation Used'),
        ),
    ]
