# Generated by Django 5.1.6 on 2025-03-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0031_rename_emp_id_benefits_emp_alter_activitylist_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefits',
            old_name='emp',
            new_name='employee',
        ),
    ]
