# Generated by Django 5.1.6 on 2025-03-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0032_rename_emp_benefits_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='pers',
        ),
    ]
