# Generated by Django 5.1.6 on 2025-03-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0033_remove_benefits_pers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='employee_id',
        ),
    ]
