# Generated by Django 5.1.6 on 2025-03-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0034_rename_emp_id_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='board_share_hrly',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='fringe',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='life_hrly',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='medicare',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='monthly_hours',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='percent_leave',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='plar',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='sick',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='total_comp',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='total_hrly',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='vacation',
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='wc',
        ),
    ]
