# Generated by Django 5.1.6 on 2025-04-03 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0035_remove_benefits_board_share_hrly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('type', models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], max_length=10, verbose_name='Type')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('payType', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10, verbose_name='Payment Type')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.item')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.line')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people')),
            ],
        ),
    ]
