# Generated by Django 5.1.6 on 2025-04-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0036_transaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transactions',
        ),
    ]
