# Generated by Django 5.1.6 on 2025-04-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0037_alter_transaction_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name_id',
            new_name='people_id',
        ),
    ]
