# Generated by Django 5.1.6 on 2025-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0038_rename_name_id_people_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payType',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check')], max_length=10, verbose_name='Payment Type'),
        ),
    ]
