# Generated by Django 5.1.6 on 2025-04-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0040_accesscontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'Variables',
            },
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='fphs',
            field=models.CharField(max_length=20, verbose_name='FPHS'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dept_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(verbose_name='DoB'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.CharField(max_length=11, verbose_name='SSN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='yos',
            field=models.FloatField(verbose_name='YoS'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_cash_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cash Balance'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='mac_elig',
            field=models.BooleanField(verbose_name='MACE'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sof',
            field=models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=10, verbose_name='SoF'),
        ),
        migrations.AlterField(
            model_name='item',
            name='line_item',
            field=models.CharField(max_length=255, verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budget_spent',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget Spent'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_budgeted',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budgeted'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_encumbered',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Encumbered'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_total_income',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Income'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grli',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GLI'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='odhafr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ODHAFR'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_num',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='PO Number'),
        ),
    ]
