# Generated by Django 5.1.6 on 2025-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0041_variable_alter_activitylist_fphs_alter_dept_dept_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
