# Generated by Django 5.1.6 on 2025-04-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0043_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clockify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('billableRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billableAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ActivityList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.activitylist')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.dept')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.employee')),
            ],
            options={
                'db_table': 'Clockify',
            },
        ),
    ]
