# Generated by Django 5.1.6 on 2025-04-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0044_clockify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockify',
            name='endDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clockify',
            name='startDate',
            field=models.CharField(max_length=255),
        ),
    ]
