# Generated by Django 5.1.6 on 2025-04-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0045_alter_clockify_enddate_alter_clockify_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockify',
            old_name='ActivityList',
            new_name='program',
        ),
    ]
