# Generated by Django 5.1.6 on 2025-04-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0046_rename_activitylist_clockify_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockify',
            old_name='program',
            new_name='ActivityList',
        ),
    ]
