# Generated by Django 5.1.6 on 2025-04-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0047_rename_program_clockify_activitylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylist',
            old_name='program_id',
            new_name='ActivityList_id',
        ),
    ]
