# Generated by Django 5.1.6 on 2025-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0048_rename_program_id_activitylist_activitylist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockify',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
            preserve_default=False,
        ),
    ]
