# Generated by Django 5.1.6 on 2025-04-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0049_clockify_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockify',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.fund'),
            preserve_default=False,
        ),
    ]
