# Generated by Django 5.1.6 on 2025-04-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0050_clockify_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockify',
            name='fund',
        ),
    ]
