# Generated by Django 5.1.6 on 2025-06-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0051_remove_clockify_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='activityList',
            new_name='ActivityList',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='comp_time_used',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_hours',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_rate',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='sick_used',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='vacation_used',
        ),
    ]
