# Generated by Django 5.1.6 on 2025-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0052_rename_activitylist_payroll_activitylist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='beg_date',
            field=models.CharField(max_length=20, verbose_name='Beginning Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.CharField(max_length=20, verbose_name='End Date'),
        ),
    ]
