# Generated by Django 5.1.6 on 2025-06-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0053_alter_payroll_beg_date_alter_payroll_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodStart', models.DateField()),
                ('periodEnd', models.DateField()),
            ],
            options={
                'db_table': 'PayPeriod',
            },
        ),
    ]
