# Generated by Django 5.1.6 on 2025-06-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0055_payroll_payperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='payperiod',
        ),
    ]
