# Generated by Django 5.1.6 on 2025-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0056_remove_payroll_payperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='beg_date',
            field=models.DateField(max_length=20, verbose_name='Beginning Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(max_length=20, verbose_name='End Date'),
        ),
    ]
