# Generated by Django 5.1.6 on 2025-06-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0057_alter_payroll_beg_date_alter_payroll_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='periodID',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
