# Generated by Django 5.1.6 on 2025-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0058_payperiod_periodid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payperiod',
            name='id',
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='periodID',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
