# Generated by Django 5.1.6 on 2025-06-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0062_rename_periodid_payperiod_payperiod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payperiod',
            old_name='payperiod_id',
            new_name='id',
        ),
    ]
