# Generated by Django 5.1.6 on 2025-06-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0063_rename_payperiod_id_payperiod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payperiod',
            old_name='id',
            new_name='payperiod_id',
        ),
    ]
