# Generated by Django 5.1.6 on 2025-06-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0064_rename_id_payperiod_payperiod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gen_pay_fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gen_pay_fund', to='WCHDApp.fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_pay_fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sick_pay_fund', to='WCHDApp.fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='vac_pay_fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vac_pay_fund', to='WCHDApp.fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='payperiod_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Pay Period'),
        ),
    ]
