# Generated by Django 5.1.6 on 2025-06-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0065_employee_gen_pay_fund_employee_sick_pay_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comp_pay_fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_pay_fund', to='WCHDApp.fund'),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday_pay_fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holiday_pay_fund', to='WCHDApp.fund'),
        ),
    ]
