# Generated by Django 5.1.6 on 2025-06-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0066_employee_comp_pay_fund_employee_holiday_pay_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comp_pay_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_pay_fund', to='WCHDApp.fund'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='holiday_pay_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holiday_pay_fund', to='WCHDApp.fund'),
        ),
    ]
