# Generated by Django 5.1.6 on 2025-06-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0067_alter_employee_comp_pay_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mac_pay_fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_pay_fund', to='WCHDApp.fund'),
        ),
    ]
