# Generated by Django 5.1.6 on 2025-06-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0068_employee_mac_pay_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mac_pay_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mac_pay_fund', to='WCHDApp.fund'),
        ),
    ]
