# Generated by Django 5.1.6 on 2025-06-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0069_alter_employee_mac_pay_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('warrant', models.IntegerField(max_length=20, verbose_name='Warrant')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('odhafr', models.CharField(max_length=50, verbose_name='ODH AFR')),
                ('ActivityList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.activitylist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.line')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.people')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('payType', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check')], max_length=20, verbose_name='Payment Type')),
                ('confirmation', models.CharField(max_length=500, verbose_name='Confirmation')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('odhafr', models.CharField(max_length=50, verbose_name='ODH AFR')),
                ('ActivityList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.activitylist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.line')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.people')),
            ],
            options={
                'db_table': 'Revenue',
            },
        ),
    ]
