# Generated by Django 5.1.6 on 2025-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0070_expense_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='warrant',
            field=models.IntegerField(verbose_name='Warrant'),
        ),
    ]
