# Generated by Django 5.1.6 on 2025-06-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0073_expense_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Item ID')),
                ('fund_type', models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=50, verbose_name='Fund Type')),
                ('fund_year', models.IntegerField(verbose_name='Fund Year')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('line_item', models.CharField(max_length=255, verbose_name='Line')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('fee_based', models.BooleanField(verbose_name='Fee Based')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.line')),
            ],
            options={
                'db_table': 'Grant Items',
            },
        ),
        migrations.CreateModel(
            name='GrantExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('grantItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grantitem')),
            ],
            options={
                'db_table': 'Grant Expenses',
            },
        ),
        migrations.RenameModel(
            old_name='Grants',
            new_name='Grant',
        ),
        migrations.CreateModel(
            name='GrantLine',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Line ID')),
                ('fund_year', models.SmallIntegerField(verbose_name='Fund Year')),
                ('line_name', models.CharField(max_length=255, verbose_name='Line Name')),
                ('line_budgeted', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budgeted')),
                ('line_encumbered', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Encumbered')),
                ('line_budget_spent', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget Spent')),
                ('line_total_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Income')),
                ('cofund', models.CharField(max_length=3, verbose_name='CoFund')),
                ('gen_ledger', models.IntegerField(verbose_name='General Ledger')),
                ('county_code', models.CharField(max_length=4, verbose_name='County Code')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grant')),
            ],
            options={
                'db_table': 'Grant Lines',
            },
        ),
    ]
