# Generated by Django 5.1.6 on 2025-06-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0074_grantitem_grantexpense_rename_grants_grant_grantline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='fund',
        ),
        migrations.CreateModel(
            name='GrantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grant')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='fund',
            field=models.ManyToManyField(through='WCHDApp.GrantAllocation', to='WCHDApp.fund'),
        ),
    ]
