# Generated by Django 5.1.6 on 2025-06-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0075_remove_grant_fund_grantallocation_grant_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='fund',
            new_name='funds',
        ),
    ]
