# Generated by Django 5.1.6 on 2025-06-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0076_rename_fund_grant_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantexpense',
            name='grantItem',
        ),
        migrations.AddField(
            model_name='grantexpense',
            name='grantLine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grantline'),
            preserve_default=False,
        ),
    ]
