# Generated by Django 5.1.6 on 2025-06-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0077_remove_grantexpense_grantitem_grantexpense_grantline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
    ]
