# Generated by Django 5.1.6 on 2025-06-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0078_alter_grantallocation_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='funds',
            new_name='fund',
        ),
    ]
