# Generated by Django 5.1.6 on 2025-07-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0079_rename_funds_grant_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantline',
            old_name='line_id',
            new_name='grantline_id',
        ),
    ]
