# Generated by Django 5.1.6 on 2025-07-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0080_rename_line_id_grantline_grantline_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantexpense',
            old_name='grantLine',
            new_name='grantline',
        ),
    ]
