# Generated by Django 5.1.6 on 2025-07-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0081_rename_grantline_grantexpense_grantline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantexpense',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fund', to='WCHDApp.fund'),
        ),
    ]
