# Generated by Django 5.1.6 on 2025-07-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0083_alter_grantexpense_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantexpense',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='grantexpense',
            name='grantline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grantline', verbose_name='Grant Line'),
        ),
    ]
