# Generated by Django 5.1.6 on 2025-07-07 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0084_alter_grantexpense_fund_alter_grantexpense_grantline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='fund',
        ),
        migrations.AddField(
            model_name='grant',
            name='fund',
            field=models.ForeignKey(default=5555, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund'),
            preserve_default=False,
        ),
    ]
