# Generated by Django 5.1.6 on 2025-07-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0085_remove_grant_fund_grant_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='grantLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.grantline'),
        ),
    ]
