# Generated by Django 5.1.6 on 2025-07-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0087_alter_expense_activitylist_alter_expense_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantline',
            name='line_encumbered',
        ),
    ]
