# Generated by Django 5.1.6 on 2025-07-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0088_remove_grantline_line_encumbered'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantline',
            name='line_budget_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Remaining'),
            preserve_default=False,
        ),
    ]
