# Generated by Django 5.1.6 on 2025-07-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0091_fund_fund_budgeted_fund_fund_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantline',
            name='receivingLine',
            field=models.BooleanField(blank=True, null=True, verbose_name='Receiving Line'),
        ),
    ]
