# Generated by Django 5.1.6 on 2025-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0092_grantline_receivingline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantline',
            name='receivingLine',
            field=models.BooleanField(verbose_name='Receiving Line'),
        ),
    ]
