# Generated by Django 5.1.6 on 2025-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0093_alter_grantline_receivingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Received'),
            preserve_default=False,
        ),
    ]
