# Generated by Django 5.1.6 on 2025-07-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0094_grant_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='grantLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.grantline', verbose_name='Grant Line'),
        ),
    ]
