# Generated by Django 5.1.6 on 2025-07-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0095_revenue_grantline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantline',
            name='receivingLine',
        ),
    ]
