# Generated by Django 5.1.6 on 2025-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0096_remove_grantline_receivingline'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantline',
            name='lineType',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Revenue', verbose_name='Line Type'),
            preserve_default=False,
        ),
    ]
