# Generated by Django 5.1.6 on 2025-07-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0098_line_linetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='WCHDApp.fund', verbose_name='Fund'),
        ),
    ]
