# Generated by Django 5.1.6 on 2025-07-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0099_alter_line_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_remaining',
        ),
    ]
