# Generated by Django 5.1.6 on 2025-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0100_remove_fund_fund_remaining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clockify',
        ),
    ]
