# Generated by Django 5.1.6 on 2025-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0101_delete_clockify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID'),
        ),
    ]
