# Generated by Django 5.1.6 on 2025-07-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0102_alter_dept_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantexpense',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='grantexpense',
            name='grantline',
        ),
        migrations.DeleteModel(
            name='GrantAllocation',
        ),
        migrations.DeleteModel(
            name='GrantExpense',
        ),
    ]
