# Generated by Django 5.1.6 on 2025-07-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0103_remove_grantexpense_fund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='comp_pay_fund',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gen_pay_fund',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='holiday_pay_fund',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mac_pay_fund',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sick_pay_fund',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vac_pay_fund',
        ),
        migrations.AddField(
            model_name='employee',
            name='specialFund',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.PROTECT, related_name='special_fund', to='WCHDApp.fund'),
            preserve_default=False,
        ),
    ]
