# Generated by Django 5.1.6 on 2025-07-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0104_remove_employee_comp_pay_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialFund',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.PROTECT, related_name='special_fund', to='WCHDApp.fund'),
        ),
    ]
