# Generated by Django 5.1.6 on 2025-08-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0108_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='activitylist',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialFund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_fund', to='WCHDApp.fund', verbose_name='Special Fund'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.dept', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='grantline',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.grant', verbose_name='Grant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people', verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='item',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='periodEnd',
            field=models.DateField(verbose_name='Periond End'),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='periodStart',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='ActivityList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.activitylist', verbose_name='Activity List'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.payperiod', verbose_name='Pay Period'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people', verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='ActivityList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.activitylist', verbose_name='Activity List'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.people', verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.fund', verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.line', verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people', verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WCHDApp.people', verbose_name='People'),
        ),
    ]
