# Generated by Django 5.1.6 on 2025-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0109_alter_activitylist_dept_alter_activitylist_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Line ID'),
        ),
    ]
