# Generated by Django 5.1.6 on 2025-08-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0110_alter_line_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='cofund',
        ),
        migrations.RemoveField(
            model_name='line',
            name='county_code',
        ),
        migrations.RemoveField(
            model_name='line',
            name='gen_ledger',
        ),
    ]
