# Generated by Django 5.1.6 on 2025-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0111_remove_line_cofund_remove_line_county_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Spent'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Income'),
        ),
    ]
