# Generated by Django 5.1.6 on 2025-08-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0112_alter_line_line_budget_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='people',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='people',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
