# Generated by Django 5.1.6 on 2025-08-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0113_remove_purchaseorder_people_remove_voucher_people_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
