# Generated by Django 5.1.6 on 2025-08-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0115_employee_adminpayfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adminPayFund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adminPayFund', to='WCHDApp.fund', verbose_name='Admin Pay Fund'),
        ),
    ]
