# Generated by Django 5.1.6 on 2025-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0116_alter_employee_adminpayfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Fund ID'),
        ),
    ]
