# Generated by Django 5.1.6 on 2025-09-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0117_alter_fund_fund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylist',
            name='odhafr',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='odhafr',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='odhafr',
        ),
    ]
