# Generated by Django 5.1.6 on 2025-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0118_remove_activitylist_odhafr_remove_expense_odhafr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='maxRevenueLines',
            field=models.IntegerField(default=1),
        ),
    ]
