# Generated by Django 5.1.6 on 2025-09-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0119_grant_maxrevenuelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line_budget_remaining',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_budget_spent',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_total_income',
        ),
    ]
