# Generated by Django 5.1.6 on 2025-09-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0120_remove_line_line_budget_remaining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantline',
            name='line_budget_remaining',
        ),
    ]
