# Generated by Django 5.1.6 on 2025-09-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0121_remove_grantline_line_budget_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantline',
            name='line_budget_spent',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='line_total_income',
        ),
    ]
