# Generated by Django 5.1.6 on 2025-09-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0122_remove_grantline_line_budget_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_budgeted',
        ),
    ]
