# Generated by Django 5.1.6 on 2025-09-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0123_remove_fund_fund_budgeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='received',
        ),
    ]
