# Generated by Django 5.1.6 on 2025-10-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0124_remove_grant_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='mac_elig',
        ),
    ]
