# Generated by Django 5.1.6 on 2025-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0125_remove_fund_mac_elig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Year'),
        ),
    ]
