# Generated by Django 5.1.6 on 2025-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0126_fund_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
