# Generated by Django 5.1.6 on 2025-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0127_alter_fund_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='revenue',
            name='reference',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reference'),
        ),
    ]
