# Generated by Django 5.1.6 on 2025-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0128_remove_revenue_confirmation_revenue_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='reference',
            field=models.CharField(max_length=500, verbose_name='Reference'),
        ),
    ]
