# Generated by Django 5.1.6 on 2025-10-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0129_alter_revenue_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantline',
            name='cofund',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='county_code',
        ),
        migrations.RemoveField(
            model_name='grantline',
            name='gen_ledger',
        ),
    ]
