# Generated by Django 5.1.6 on 2025-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0130_remove_grantline_cofund_remove_grantline_county_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='reference',
            field=models.IntegerField(verbose_name='Reference'),
        ),
    ]
