# Generated by Django 5.1.6 on 2025-10-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0131_alter_revenue_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payItem',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.PROTECT, related_name='pay_item', to='WCHDApp.item', verbose_name='Pay Item'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialPayItem',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.PROTECT, related_name='special_pay_item', to='WCHDApp.item', verbose_name='Special Pay Item'),
        ),
    ]
