# Generated by Django 5.1.6 on 2025-10-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0132_employee_payitem_employee_specialpayitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_item', to='WCHDApp.item', verbose_name='Pay Item'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialPayItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_pay_item', to='WCHDApp.item', verbose_name='Special Pay Item'),
        ),
    ]
