# Generated by Django 5.1.6 on 2025-10-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0133_alter_employee_payitem_alter_employee_specialpayitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='item',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.item', verbose_name='Item'),
        ),
    ]
