# Generated by Django 5.1.6 on 2025-10-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0134_activitylist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WCHDApp.item', verbose_name='Item'),
        ),
    ]
