# Generated by Django 5.1.6 on 2025-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0135_alter_activitylist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='ianzyarwood@gmail.com', max_length=254, verbose_name='Email'),
        ),
    ]
