# Generated by Django 5.1.6 on 2025-10-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0137_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='payType',
            field=models.CharField(choices=[('general', 'General'), ('admin', 'Admin'), ('special', 'Special')], default='general', max_length=10, verbose_name='Pay Type'),
        ),
    ]
