# Generated by Django 5.1.6 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0138_activitylist_paytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylist',
            name='payType',
            field=models.CharField(choices=[('general', 'General'), ('admin', 'Admin'), ('special', 'Special')], max_length=10, verbose_name='Pay Type'),
        ),
    ]
