# Generated by Django 5.1.6 on 2025-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0139_alter_activitylist_paytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseFullID',
            field=models.CharField(default='554-683-10/13/25-9:00', max_length=25, verbose_name='Expense Full ID'),
        ),
    ]
