# Generated by Django 5.1.6 on 2025-10-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0141_alter_expense_expensefullid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expenseFullID',
            field=models.CharField(max_length=50, verbose_name='Expense Full ID'),
        ),
    ]
