# Generated by Django 5.1.6 on 2025-10-16 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WCHDApp', '0142_alter_expense_expensefullid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date'),
        ),
    ]
